language: python
python:
  - "2.8"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install requiremets.txt
script:
  - pytest huobi_api/tests/*.py